import Link from "next/link";
import { CopyCodeBlock, LessonChecklist } from "@/components/formation/web/LessonInteractions";
import LessonPedagogyVisual from "@/components/formation/web/LessonPedagogy";
import type { WebFoundationLesson as Lesson } from "@/lib/training/web/foundations";

export default function WebFoundationLesson({ lesson, completed, requiredFor }: { lesson: Lesson; completed: boolean; requiredFor: string | null }) {
  return <main className="min-h-screen bg-slate-50 px-4 py-8 text-slate-950 sm:px-6"><div className="mx-auto max-w-5xl">
    <header className="flex items-center justify-between gap-4"><Link href="/formation/site-web" className="text-sm font-semibold text-slate-600">← Retour au module</Link><span className="rounded-full bg-slate-950 px-4 py-2 text-xs font-bold text-white">{lesson.number} / 12</span></header>
    {requiredFor && <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 font-semibold text-amber-950">Validez cette leçon avant d&apos;accéder à la leçon {requiredFor}.</div>}
    <section className="mt-6 rounded-[32px] bg-slate-950 p-7 text-white md:p-10"><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-300">PropertyMatch · Leçon {lesson.number}</p><h1 className="mt-4 text-4xl font-bold md:text-5xl">{lesson.title}</h1></section>
    <Section number="1" title="Ce que vous allez construire"><p>{lesson.build}</p></Section>
    <Section number="2" title="Résultat visible attendu"><p>{lesson.visibleResult}</p></Section>
    {lesson.installTools && <section className="mt-6 rounded-3xl border-2 border-blue-300 bg-blue-50 p-6 md:p-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">Outils à installer</p><h2 className="mt-2 text-2xl font-bold text-blue-950">Téléchargements officiels</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{lesson.installTools.map((tool) => <article key={tool.name} className="rounded-2xl bg-white p-5"><h3 className="text-lg font-bold">{tool.name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{tool.purpose}</p><a href={tool.url} target="_blank" rel="noreferrer" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-blue-700 px-4 py-2 font-bold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-blue-700">Télécharger sur le site officiel ↗</a></article>)}</div></section>}
    <Section number="3" title="Ce que vous devez déjà avoir"><BulletList items={lesson.prerequisites} /></Section>
    <Section number="4" title="Vocabulaire expliqué simplement"><dl className="grid gap-4 md:grid-cols-2">{lesson.vocabulary.map((item) => <div key={item.term} className="rounded-2xl bg-slate-50 p-4"><dt className="font-bold">{item.term}</dt><dd className="mt-2 text-sm leading-6 text-slate-600">{item.definition}</dd></div>)}</dl></Section>
    <section className="mt-6"><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">5 à 11 · Actions, commandes et code</p><h2 className="mt-2 text-3xl font-bold">Construire pas à pas dans VS Code</h2><div className="mt-5 space-y-6">{lesson.steps.map((step, index) => <article key={step.title} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm md:p-8"><p className="text-xs font-bold uppercase tracking-wider text-blue-700">Étape {index + 1}</p><h3 className="mt-2 text-2xl font-bold">{step.title}</h3>{step.path && (step.path.startsWith("http") ? <div className="mt-4 rounded-xl border border-violet-200 bg-violet-50 p-4"><p className="text-xs font-bold uppercase text-violet-700">🌐 Adresse à ouvrir dans le navigateur</p><code className="mt-2 block break-words font-bold text-violet-950">{step.path}</code></div> : <div className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="text-xs font-bold uppercase text-blue-700">📁 Chemin du dossier ou fichier</p><code className="mt-2 block break-words font-bold text-blue-950">{step.path}</code>{step.action && <p className="mt-2 text-sm text-blue-900"><strong>Action :</strong> {step.action}</p>}</div>)}<p className="mt-4 leading-7 text-slate-700">{step.instruction}</p>{step.download && <a href={step.download.url} download className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-[#07583f] px-5 py-3 font-bold text-white focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#07583f]">{step.download.label}</a>}{step.commands && <CopyCodeBlock code={step.commands.join("\n")} label="Exécuter ligne par ligne" kind="terminal" />}{step.code && <CopyCodeBlock code={step.code} label={`${step.action ?? "Code"} · ${step.path ?? "fichier"}`} kind="code" />}{step.explanation && <div className="mt-5"><h4 className="font-bold">Explication des parties importantes</h4><BulletList items={step.explanation} /></div>}<div className="mt-5 rounded-xl border-l-4 border-emerald-600 bg-emerald-50 p-4 text-emerald-950"><strong>Sauvegarde et résultat attendu :</strong> {step.expected}</div>{step.visual && <LessonPedagogyVisual {...step.visual} />}</article>)}</div></section>
    <LessonChecklist items={lesson.checklist} />
    <Section number="13" title="Erreurs fréquentes et corrections"><div className="space-y-4">{lesson.errors.map((error) => <article key={error.problem} className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3 className="font-bold text-amber-950">{error.problem}</h3><p className="mt-2 text-sm leading-6 text-amber-900"><strong>Cause :</strong> {error.cause}</p><p className="mt-2 text-sm leading-6 text-amber-900"><strong>Correction :</strong> {error.correction}</p></article>)}</div></Section>
    <Section number="14" title="Petit exercice guidé"><OrderedList items={lesson.exercise} /></Section>
    <Section number="15" title="Ce que vous savez maintenant faire"><BulletList items={lesson.summary} /></Section>
    <section className="mt-6 rounded-3xl bg-slate-950 p-7 text-white"><p className="text-sm leading-6 text-slate-300">{completed ? "Cette leçon est validée. Un nouvel essai ne peut effacer ni votre meilleur score ni votre première date de réussite." : "Seul le QCM sécurisé valide la leçon. Les cases cochées ne modifient pas la progression."}</p><Link href={`/formation/site-web/${lesson.slug}/qcm`} className="mt-5 inline-flex rounded-xl bg-white px-5 py-3 font-bold text-slate-950">{completed ? "Refaire le QCM sécurisé" : "Passer le QCM sécurisé"} →</Link></section>
  </div></main>;
}

function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 md:p-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-blue-700">{number}</p><h2 className="mt-2 text-2xl font-bold">{title}</h2><div className="mt-4 leading-7 text-slate-700">{children}</div></section>; }
function BulletList({ items }: { items: readonly string[] }) { return <ul className="mt-3 list-disc space-y-2 pl-5">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }
function OrderedList({ items }: { items: readonly string[] }) { return <ol className="mt-3 list-decimal space-y-3 pl-5">{items.map((item) => <li key={item}>{item}</li>)}</ol>; }
