import { webLessonCatalog } from "../catalog.ts";
import {
  lessonFiveDataCode,
  lessonFivePageCode,
  lessonFiveStarterDataCode,
  lessonFiveTypeCode,
  lessonFourGlobalsCode,
  lessonFourPageCode,
  lessonSixComponents,
  lessonSixPageCode,
} from "./checkpoints.ts";
import type { WebFoundationLesson } from "./foundations.ts";

export const webLessonsFourToSix = [
  {
    id: webLessonCatalog[3].id,
    slug: "04",
    number: "04",
    title: webLessonCatalog[3].title,
    build: "Transformer la structure HTML de PropertyMatch en une interface proche de la référence visuelle, avec Tailwind et sans ajouter de nouvelle fonctionnalité.",
    visibleResult: "L’accueil possède un header blanc, un hero bleu marine, un formulaire ivoire, des indicateurs honnêtes et une mise en page adaptée au mobile, à la tablette et à l’ordinateur.",
    prerequisites: ["Les leçons 1 à 3 sont validées.", "La structure PropertyMatch de la leçon 3 apparaît sur localhost:3000.", "Le terminal affiche toujours npm run dev sans erreur."],
    vocabulary: [
      { term: "CSS", definition: "Le langage qui contrôle l’apparence : couleurs, tailles, espaces et disposition." },
      { term: "Classe utilitaire", definition: "Une classe Tailwind courte qui applique une seule règle, par exemple text-white pour un texte blanc." },
      { term: "Couleur", definition: "Une valeur qui donne une teinte au fond, au texte ou à une bordure." },
      { term: "Classe Tailwind", definition: "Un petit nom placé dans className qui applique une règle visuelle précise, par exemple p-5 pour un espace intérieur." },
      { term: "Espacement", definition: "La distance intérieure ou extérieure qui empêche les éléments de se toucher." },
      { term: "Largeur maximale", definition: "Une limite qui empêche le contenu de devenir trop étiré sur un grand écran." },
      { term: "Flex", definition: "Une disposition pratique pour aligner des éléments sur une ligne ou une colonne." },
      { term: "Grid", definition: "Une grille qui répartit plusieurs éléments dans des colonnes régulières." },
      { term: "Breakpoint", definition: "Une largeur à partir de laquelle une variante s’applique ; md: vise notamment les écrans moyens." },
      { term: "Responsive", definition: "Une interface qui reste lisible et utilisable quelle que soit la largeur de l’écran." },
      { term: "Hover", definition: "L’état visuel affiché quand la souris survole un élément." },
      { term: "Focus", definition: "L’état visible d’un lien ou champ sélectionné au clavier avec Tab." },
    ],
    steps: [
      {
        title: "Comparer la structure brute et la cible",
        instruction: "Gardez localhost:3000 ouvert. Comparez la page simple de la leçon 3 au checkpoint de cette leçon. Repérez seulement les changements d’apparence : couleurs, espaces, largeur, grille et typographie. Les contenus et les fonctions restent identiques.",
        action: "Conserver",
        path: "http://localhost:3000",
        expected: "Vous savez distinguer la structure déjà présente du design que Tailwind va ajouter.",
        visual: { src: "/formation/site-web/lessons/04/before-after.svg", alt: "Comparaison annotée de PropertyMatch avant et après les styles Tailwind", caption: "Étape 1 — Tailwind change l’apparence, pas le rôle des zones de la page.", width: 1200, height: 640, placement: 1 },
      },
      {
        title: "Retrouver les className dans la page",
        instruction: "Dans l’Explorateur, ouvrez app/page.tsx. Le checkpoint de la leçon 3 n’a presque aucun className. En React, on écrit className à la place de l’attribut HTML class, car class est déjà un mot réservé en JavaScript. Ne modifiez encore rien.",
        action: "Ouvrir",
        path: "app/page.tsx",
        expected: "Vous avez identifié le fichier à remplacer et compris où les classes Tailwind seront écrites.",
        visual: { src: "/formation/site-web/lessons/04/lesson-03-before.png", alt: "Rendu réel simple de PropertyMatch à la fin de la leçon trois", caption: "Étape 2 — état de départ réel avant l’ajout des classes Tailwind.", width: 1200, height: 760, placement: 2 },
      },
      {
        title: "Préparer les styles communs",
        instruction: "Dans l’Explorateur VS Code, ouvrez app puis globals.css. Sélectionnez tout, remplacez le fichier par le bloc ci-dessous et sauvegardez. @import charge Tailwind ; les autres lignes donnent une base cohérente et un focus visible au clavier.",
        action: "Remplacer entièrement",
        path: "app/globals.css",
        code: lessonFourGlobalsCode,
        explanation: ["box-sizing rend les dimensions plus prévisibles.", "body fixe le fond ivoire, le texte marine et une police lisible.", "font: inherit évite des textes incohérents dans les champs.", "focus-visible dessine un contour vert lorsqu’un contrôle reçoit le clavier."],
        expected: "La page conserve sa structure et adopte déjà le fond ivoire et le texte marine.",
      },
      {
        title: "Appliquer le design complet du checkpoint",
        instruction: "Ouvrez app/page.tsx, sélectionnez tout, collez ce checkpoint complet puis sauvegardez. Lisez ensuite chaque grande zone avant de revenir dans le navigateur. Les classes sont nombreuses parce qu’elles décrivent tout le design, mais chaque groupe est expliqué ci-dessous.",
        action: "Remplacer entièrement",
        path: "app/page.tsx",
        code: lessonFourPageCode,
        explanation: ["bg, text et border définissent couleurs et bordures.", "p, px, py, mt et gap créent les espaces.", "flex aligne le logo et la navigation ; grid organise les champs.", "max-w et mx-auto limitent puis centrent le contenu.", "rounded et shadow donnent la carte ivoire du formulaire.", "md: et lg: modifient la disposition uniquement quand l’écran devient assez large."],
        expected: "Le rendu correspond au checkpoint Tailwind, sans image de logement ni recherche fonctionnelle.",
        visual: { src: "/formation/site-web/lessons/04/checkpoint-responsive.svg", alt: "Checkpoint schématique fidèle de l’accueil PropertyMatch sur ordinateur et mobile", caption: "Étape 3 — aperçu déterministe du checkpoint : design responsive uniquement, sans fonction future.", width: 1200, height: 650, placement: 3 },
      },
      {
        title: "Comprendre flex, grid et les breakpoints",
        instruction: "Dans page.tsx, recherchez flex puis grid. Réduisez ensuite progressivement la fenêtre du navigateur. Sans préfixe, une classe s’applique partout. md: s’ajoute à partir d’un écran moyen et lg: à partir d’un grand écran.",
        action: "Conserver",
        path: "app/page.tsx",
        explanation: ["Le header est empilé par défaut, puis md:flex-row le place sur une ligne.", "Le formulaire a une colonne par défaut, md:grid-cols-2 puis lg:grid-cols-4.", "Les espacements augmentent progressivement avec md: et lg:.", "Il ne faut pas recopier une version différente de la page pour chaque écran."],
        expected: "Le même code passe de une à deux puis quatre colonnes selon la largeur.",
        visual: { src: "/formation/site-web/lessons/04/flex-grid-responsive.svg", alt: "Schéma comparant flex, grid et les breakpoints mobile tablette ordinateur", caption: "Étape 4 — une seule structure, trois dispositions obtenues avec les préfixes responsive.", width: 1200, height: 620, placement: 4 },
      },
      {
        title: "Vérifier les trois largeurs",
        instruction: "Ouvrez les outils de développement du navigateur, activez le mode responsive puis testez environ 390 px, 768 px et 1440 px. Faites défiler toute la page. Aucun texte ne doit sortir de l’écran et tous les champs doivent rester utilisables.",
        action: "Conserver",
        path: "http://localhost:3000",
        expected: "Le formulaire affiche une colonne sur mobile, deux sur tablette et quatre sur ordinateur.",
        visual: { src: "/formation/site-web/lessons/04/checkpoint-responsive.svg", alt: "Comparaison schématique du checkpoint PropertyMatch sur ordinateur et mobile", caption: "Étape 5 — la partie droite montre l’empilement mobile attendu, sans défilement horizontal.", width: 1200, height: 650, placement: 5 },
      },
    ],
    checklist: ["globals.css et page.tsx sont sauvegardés.", "Le terminal ne montre aucune erreur.", "Le header est blanc et le hero bleu marine.", "Le formulaire reste visuel et son bouton ne lance aucune recherche.", "Le rendu fonctionne à 390, 768 et 1440 px.", "Aucune carte, image, donnée, recherche, note ou favori n’a été ajouté."],
    errors: [
      { problem: "Les classes n’ont aucun effet", cause: "globals.css ne charge plus Tailwind ou le mauvais fichier a été modifié.", correction: "Vérifiez app/globals.css et sa première ligne @import \"tailwindcss\";, puis sauvegardez." },
      { problem: "Une ligne sort de l’écran sur mobile", cause: "Une largeur fixe ou une grille trop large a remplacé les classes du checkpoint.", correction: "Reprenez min-h, w-full et les variantes md:/lg: du bloc fourni." },
      { problem: "Le bouton semble fonctionnel mais rien ne se passe", cause: "La recherche n’est volontairement pas programmée dans cette leçon.", correction: "Conservez type=\"button\" ; la logique de recherche arrivera plus tard." },
    ],
    exercise: ["Dans le hero, remplacez md:text-5xl par md:text-6xl.", "Observez la différence sur ordinateur puis sur mobile.", "Rétablissez md:text-5xl et sauvegardez pour retrouver le checkpoint."],
    summary: ["Ajouter des classes Tailwind dans className.", "Reconnaître couleurs, espacements, bordures et typographie.", "Utiliser flex et grid pour organiser une interface.", "Adapter un même composant avec md: et lg:.", "Tester réellement plusieurs largeurs d’écran."],
  },
  {
    id: webLessonCatalog[4].id,
    slug: "05",
    number: "05",
    title: webLessonCatalog[4].title,
    build: "Comprendre précisément trois objets, puis installer le catalogue complet de quinze logements fictifs locaux sans afficher encore les cartes.",
    visibleResult: "L’interface reste identique, mais l’indicateur affiche automatiquement 15 locations fictives et TypeScript vérifie chaque objet.",
    prerequisites: ["La leçon 4 est validée.", "Le checkpoint Tailwind fonctionne sur mobile et ordinateur.", "Vous savez ouvrir un fichier par son chemin dans l’Explorateur."],
    vocabulary: [
      { term: "Donnée", definition: "Une information manipulée par le programme, comme une ville ou un loyer." },
      { term: "Objet", definition: "Un groupe de propriétés qui décrivent ici un logement unique." },
      { term: "Propriété", definition: "Une information nommée d’un objet, par exemple city ou monthlyRent." },
      { term: "Type", definition: "Un contrat TypeScript qui décrit les propriétés attendues et leur nature." },
      { term: "Chaîne de caractères", definition: "Un texte placé entre guillemets, appelé string en TypeScript." },
      { term: "Tableau", definition: "Une liste ordonnée placée entre crochets, ici la liste des logements." },
      { term: "Identifiant", definition: "Une valeur stable qui distingue un logement de tous les autres, comme id ou slug." },
      { term: "Import", definition: "Une instruction qui rend disponible dans un fichier ce qui est exporté par un autre." },
    ],
    steps: [
      {
        title: "Visualiser la circulation des données",
        instruction: "Avant d’écrire, suivez le schéma : le type décrit la forme, le fichier de données respecte cette forme et page.tsx importe le tableau. Les quinze logements sont fictifs et restent dans un fichier sur votre ordinateur : aucune base de données et aucune connexion Internet ne sont utilisées.",
        action: "Conserver",
        path: "Cette page AI Academy dans le navigateur",
        expected: "Vous pouvez expliquer la différence entre le contrat Property et les quinze objets fictifs.",
        visual: { src: "/formation/site-web/lessons/05/data-flow.svg", alt: "Schéma du type Property vers les données locales puis la page PropertyMatch", caption: "Étape 1 — le type vérifie les données avant que la page utilise leur nombre.", width: 1200, height: 500, placement: 1 },
      },
      {
        title: "Créer le contrat Property",
        instruction: "Dans l’Explorateur, créez un dossier types à la racine, puis un fichier property.ts dedans. Collez le bloc complet et sauvegardez. Chaque ligne nomme une information obligatoire et précise si elle contient un nombre, un texte ou un booléen vrai/faux.",
        action: "Créer",
        path: "types/property.ts",
        code: lessonFiveTypeCode,
        explanation: ["export rend le type disponible ailleurs.", "string représente du texte ; number un nombre.", "boolean vaut seulement true ou false.", "imagePath et imageAlt préparent des images locales qui seront utilisées plus tard."],
        expected: "types/property.ts apparaît dans l’Explorateur sans erreur rouge.",
        visual: { src: "/formation/site-web/lessons/05/property-type.svg", alt: "Objet logement annoté avec les types string number et boolean", caption: "Étape 2 — chaque valeur doit respecter le contrat défini dans Property.", width: 1200, height: 560, placement: 2 },
      },
      {
        title: "Lire l’aide TypeScript dans VS Code",
        instruction: "Dans property.ts, placez la souris sur le mot Property sans cliquer. VS Code affiche une petite infobulle avec la forme du type. Cette aide vient de TypeScript et ne modifie pas le fichier.",
        action: "Conserver",
        path: "types/property.ts",
        expected: "Une infobulle décrit Property ; vous savez la fermer en éloignant la souris ou avec Échap.",
        visual: { src: "/formation/site-web/lessons/05/typescript-tooltip.svg", alt: "Infobulle TypeScript de VS Code affichant la structure du type Property", caption: "Étape 3 — l’infobulle permet de vérifier un type sans quitter le fichier.", width: 1200, height: 560, placement: 3 },
      },
      {
        title: "Comprendre le premier objet",
        instruction: "Lisez d’abord seulement le premier logement du bloc suivant : id et slug l’identifient ; title et city sont des textes ; monthlyRent est mensuel ; surface, bedrooms et bathrooms sont des nombres ; hasBalcony est un booléen. Les chemins d’image sont préparés mais aucune image n’est encore affichée.",
        action: "Conserver",
        path: "data/properties.ts",
        explanation: ["Une paire propriété: valeur renseigne une information.", "Une virgule sépare deux propriétés ou deux objets.", "Le tableau commence par [ et se termine par ].", "Les trois premiers objets servent de modèle détaillé avant l’installation du catalogue complet."],
        expected: "Vous savez relier chaque valeur du premier objet à une ligne du type Property.",
      },
      {
        title: "Créer les trois logements locaux",
        instruction: "Créez le dossier data à la racine, puis properties.ts. Collez le fichier complet et sauvegardez. Ne modifiez pas encore page.tsx : vérifiez d’abord le panneau Problèmes de VS Code.",
        action: "Créer",
        path: "data/properties.ts",
        code: lessonFiveStarterDataCode,
        expected: "Le panneau Problèmes ne signale aucune propriété absente ou de mauvais type.",
        visual: { src: "/formation/site-web/lessons/05/local-data-tree.svg", alt: "Arborescence PropertyMatch avec les dossiers types et data nouvellement créés", caption: "Étape 4 — types et données sont séparés du fichier de page.", width: 1200, height: 620, placement: 4 },
      },
      {
        title: "Compléter le catalogue de démonstration",
        instruction: "Vous n’avez pas à inventer ni à saisir manuellement les douze objets restants. Dans data/properties.ts, sélectionnez tout, remplacez le fichier par le bloc complet ci-dessous puis sauvegardez. Il reprend les quinze locations fictives de l’application PropertyMatch de référence, uniquement avec les champs déjà enseignés. Les descriptions, équipements, étages et disponibilités seront ajoutés avec les fiches détaillées à la leçon 10.",
        action: "Remplacer entièrement",
        path: "data/properties.ts",
        code: lessonFiveDataCode,
        explanation: ["Les quinze id vont de pm-001 à pm-015 et ne se répètent pas.", "Chaque slug est stable et unique.", "Chaque objet respecte exactement le type Property.", "Les villes et quartiers sont génériques : aucune adresse personnelle réelle n’est enregistrée.", "Tous les chemins d’image sont locaux et aucune donnée distante n’est chargée."],
        expected: "data/properties.ts contient exactement quinze objets et le panneau Problèmes reste vide.",
      },
      {
        title: "Relier les données sans créer les cartes",
        instruction: "Ouvrez app/page.tsx, remplacez-le entièrement par ce checkpoint et sauvegardez. La seule évolution visible est {properties.length} : TypeScript lit le tableau et React affiche automatiquement son nombre d’éléments.",
        action: "Remplacer entièrement",
        path: "app/page.tsx",
        code: lessonFivePageCode,
        explanation: ["import récupère properties depuis data/properties.ts.", "@/ signifie la racine du projet.", "properties.length vaut 15 parce que le tableau contient quinze objets.", "Le nombre n’est pas écrit manuellement : si le catalogue change plus tard, length garde automatiquement l’indicateur exact.", "Les objets ne sont pas encore transformés en cartes : ce sera une leçon ultérieure."],
        expected: "L’indicateur affiche 15 locations fictives et locales ; le reste de la page ne change pas.",
        visual: { src: "/formation/site-web/lessons/05/checkpoint-catalogue.svg", alt: "Checkpoint schématique affichant quinze logements calculés avec properties.length", caption: "Dernière étape — le compteur réel vaut 15 ; aucune carte n’est encore affichée.", width: 1200, height: 600, placement: 6 },
      },
    ],
    checklist: ["types/property.ts définit les onze propriétés attendues.", "data/properties.ts contient exactement quinze objets fictifs.", "properties.length vaut 15.", "Chaque id et chaque slug sont uniques.", "Chaque objet respecte le type Property.", "Aucune adresse personnelle réelle ni donnée distante n’est présente.", "La page importe properties avec @/data/properties.", "L’indicateur affiche le nombre calculé 15.", "Aucune carte ni image de logement n’est rendue."],
    errors: [
      { problem: "Type 'string' is not assignable to type 'number'", cause: "Un nombre a été placé entre guillemets, par exemple monthlyRent: \"1250\".", correction: "Retirez les guillemets pour écrire monthlyRent: 1250." },
      { problem: "Cannot find module '@/data/properties'", cause: "Le fichier ou le dossier n’a pas exactement le bon nom.", correction: "Vérifiez le chemin data/properties.ts à la racine et sauvegardez-le." },
      { problem: "La page n’affiche pas le nombre 15", cause: "Le catalogue complet n’a pas remplacé les trois objets de départ ou {properties.length} a été recopié comme texte ordinaire.", correction: "Reprenez l’étape « Compléter le catalogue de démonstration », puis vérifiez l’import de page.tsx." },
    ],
    exercise: ["Dans data/properties.ts, changez temporairement le loyer de Lyon en texte avec des guillemets.", "Observez l’erreur TypeScript dans le panneau Problèmes.", "Rétablissez le nombre 1480, sauvegardez et vérifiez que l’erreur disparaît."],
    summary: ["Décrire un logement avec un type TypeScript.", "Comprendre trois objets puis installer un catalogue complet de quinze logements.", "Vérifier des identifiants et slugs uniques.", "Importer des données fictives locales dans une page.", "Utiliser length pour conserver un compteur exact sans anticiper l’affichage des cartes."],
  },
  {
    id: webLessonCatalog[5].id,
    slug: "06",
    number: "06",
    title: webLessonCatalog[5].title,
    build: "Découper la grande page en petits composants React nommés sans modifier son apparence ni ajouter les cartes.",
    visibleResult: "PropertyMatch reste visuellement identique, tandis que app/page.tsx devient court et assemble Logo, Header, SearchForm, Hero, StatsStrip, FeaturedProperties et Footer.",
    prerequisites: ["La leçon 5 est validée.", "Le tableau local contient trois logements valides.", "L’indicateur de l’accueil affiche 3 locations fictives."],
    vocabulary: [
      { term: "Composant", definition: "Une fonction React nommée qui retourne une partie précise de l’interface." },
      { term: "Fonction", definition: "Un bloc de code nommé que React peut appeler pour obtenir une partie de l’interface." },
      { term: "Réutilisable", definition: "Qui peut être appelé à plusieurs endroits sans recopier tout son code." },
      { term: "export default", definition: "L’instruction qui rend un composant principal importable depuis un autre fichier." },
      { term: "Import", definition: "La ligne qui donne accès à un composant exporté ailleurs." },
      { term: "Arborescence", definition: "L’organisation des dossiers et fichiers visible dans l’Explorateur." },
      { term: "Responsabilité", definition: "Le rôle unique et clairement nommé d’un fichier ou d’un composant." },
      { term: "Composant serveur", definition: "Dans l’App Router, un composant rendu par Next.js côté serveur par défaut tant qu’il n’utilise pas \"use client\"." },
    ],
    steps: [
      {
        title: "Passer d’un bloc unique à des composants",
        instruction: "Observez le schéma. La page actuelle contient toutes les zones. Après le découpage, chaque fichier possède un rôle mais le navigateur reçoit la même interface. Cette leçon déplace du JSX ; elle ne change pas les données ni le design.",
        action: "Conserver",
        path: "Cette page AI Academy dans le navigateur",
        expected: "Vous pouvez nommer les sept composants et leur place dans la page.",
        visual: { src: "/formation/site-web/lessons/06/components-map.svg", alt: "Transformation d’une grande page React en sept composants PropertyMatch", caption: "Étape 1 — le découpage améliore l’organisation sans changer le résultat visuel.", width: 1200, height: 650, placement: 1 },
      },
      {
        title: "Lire un import et une balise de composant",
        instruction: "Observez le schéma avant de créer les fichiers. Le chemin après from indique où trouver le fichier. Le nom Header commence par une majuscule dans l’import et dans la balise fermée <Header />. Le préfixe @/ désigne la racine du projet.",
        action: "Conserver",
        path: "Cette page AI Academy dans le navigateur",
        expected: "Vous savez relier un import, un fichier et la balise React correspondante.",
        visual: { src: "/formation/site-web/lessons/06/import-component.svg", alt: "Import React annoté reliant Header.tsx à la balise Header autofermée", caption: "Étape 2 — le nom et la casse doivent être identiques dans le fichier, l’import et la balise.", width: 1200, height: 500, placement: 2 },
      },
      ...Object.entries(lessonSixComponents).map(([path, code], index) => ({
        title: `Créer ${path.replace("components/", "")}`,
        instruction: index === 0 ? "Créez d’abord le dossier components à la racine. À l’intérieur, créez le fichier indiqué, collez son contenu complet et sauvegardez." : "Dans le dossier components, créez exactement le fichier indiqué, collez son contenu complet et sauvegardez. La page peut signaler provisoirement des éléments inutilisés : l’assemblage final arrive après tous les fichiers.",
        action: "Créer" as const,
        path,
        code,
        explanation: index === 0 ? ["Le nom du composant commence par une majuscule.", "La fonction retourne le petit bloc JSX du logo.", "export default permettra au Header de l’importer."] : ["Le nom du fichier correspond au nom du composant.", "Le composant conserve les classes Tailwind du checkpoint précédent.", "Les imports relient seulement les composants qui en ont besoin."],
        expected: `${path} est enregistré dans le dossier components.`,
      })),
      {
        title: "Assembler les composants dans la page",
        instruction: "Une fois les sept fichiers créés, ouvrez app/page.tsx, sélectionnez tout, collez ce fichier court et sauvegardez. Chaque balise avec une majuscule appelle le composant importé correspondant.",
        action: "Remplacer entièrement",
        path: "app/page.tsx",
        code: lessonSixPageCode,
        explanation: ["Les cinq imports donnent accès aux composants placés directement dans la page.", "Hero importe lui-même SearchForm et Header importe Logo.", "main regroupe toujours le contenu principal.", "FeaturedProperties reste un emplacement vide : les cartes viendront après cette leçon."],
        expected: "La page compile et son rendu reste identique à celui de la leçon 5.",
        visual: { src: "/formation/site-web/lessons/06/checkpoint-components.svg", alt: "Schéma comparant la page monolithique et les composants React sans changement visuel", caption: "Étape finale — l’organisation du code change, pas l’apparence dans le navigateur.", width: 1200, height: 600, placement: 9 },
      },
      {
        title: "Relire l’arborescence finale",
        instruction: "Dans l’Explorateur, repliez puis rouvrez components. Cliquez sur Header, puis Hero, puis page.tsx et suivez chaque import. Aucun fichier ne doit être placé dans app par erreur.",
        action: "Conserver",
        path: "components/ et app/page.tsx",
        expected: "Vous retrouvez le fichier responsable de chaque zone sans rechercher dans une page immense.",
        visual: { src: "/formation/site-web/lessons/06/final-tree.svg", alt: "Arborescence finale des composants React de PropertyMatch à la leçon six", caption: "Vérification — les composants restent à la racine dans components et la route reste dans app.", width: 1200, height: 680, placement: 10 },
      },
    ],
    checklist: ["Le dossier components contient sept fichiers nommés exactement.", "Header importe Logo et Hero importe SearchForm.", "StatsStrip importe les données locales.", "app/page.tsx assemble les grandes zones.", "Le terminal ne montre aucune erreur d’import.", "Le rendu avant et après le découpage est identique.", "Aucune carte, recherche, note ou favori n’a été ajouté."],
    errors: [
      { problem: "Module not found: Can't resolve '@/components/…'", cause: "Le nom, les majuscules ou le chemin du fichier diffèrent de l’import.", correction: "Comparez caractère par caractère le fichier dans components et la ligne import correspondante." },
      { problem: "Element type is invalid", cause: "Un composant n’est pas exporté par défaut ou son import ne correspond pas.", correction: "Vérifiez export default function dans le fichier et import Nom from dans son parent." },
      { problem: "La page est vide pendant la création", cause: "page.tsx a été remplacé avant que tous les composants existent.", correction: "Terminez les sept fichiers, puis recollez le checkpoint final de app/page.tsx." },
    ],
    exercise: ["Ouvrez components/Footer.tsx.", "Remplacez le texte pédagogique par « Trois locations fictives pour apprendre React ».", "Sauvegardez, observez uniquement le footer, puis rétablissez le texte du checkpoint."],
    summary: ["Définir un composant React nommé.", "Exporter puis importer un composant.", "Découper une interface selon des responsabilités.", "Lire une arborescence de composants.", "Refactoriser sans changer le rendu ni anticiper les prochaines fonctionnalités."],
  },
] satisfies readonly WebFoundationLesson[];
