import { webLessonCatalog } from "../catalog.ts";
import { lessonElevenFavoritesCode,lessonTenNavigationCode,lessonTenPropertiesCode,lessonTenPropertiesHelperCode,lessonTenPropertyTypeCode,lessonTwelveCommands,lessonTwelvePackageCode,readCheckpointSource,type FinalCheckpoint } from "./checkpoints101112.ts";
import type { WebFoundationLesson } from "./foundations.ts";
const visual=(lesson:string,name:string,alt:string,caption:string,placement:number)=>({src:`/formation/site-web/lessons/${lesson}/${name}.svg`,alt,caption,width:1200,height:600,placement});
const completeFile=(checkpoint:FinalCheckpoint,path:string,action:"Créer"|"Remplacer entièrement",instruction:string,expected:string)=>({title:`${action} ${path}`,instruction,action,path,code:readCheckpointSource(checkpoint,path),expected});
export const webLessonsTenToTwelve=[
{id:webLessonCatalog[9].id,slug:"10",number:"10",title:webLessonCatalog[9].title,build:"Enrichir les quinze locations et créer une route dynamique, un retour fidèle et une vraie page 404.",visibleResult:"Chaque carte ouvre une fiche complète ; le score reste identique et Retour aux résultats restaure les critères.",prerequisites:["Les leçons 1 à 9 sont validées.","/biens et le matching fonctionnent."],vocabulary:[{term:"Slug",definition:"Identifiant lisible et stable placé dans l’URL."},{term:"Route dynamique",definition:"Une page dont un segment entre crochets varie."},{term:".find()",definition:"Recherche le premier objet correspondant."},{term:"notFound()",definition:"Demande à Next.js d’afficher la page introuvable."},{term:"Métadonnées",definition:"Titre et description propres à une page."},{term:"Propriété facultative",definition:"Champ marqué ? qui peut être absent."}],steps:[
{title:"Comprendre [slug]",instruction:"Observez comment lumineux-bastille devient params.slug. La page recherche ce slug ; absence signifie contenu introuvable, pas panne technique.",action:"Conserver",path:"/biens/[slug]",expected:"Vous distinguez route dynamique et URL réelle.",visual:visual("10","dynamic-route","Schéma de la route dynamique vers une fiche ou la page 404","Étape 1 — params.slug relie l’URL au catalogue local.",1)},
{title:"Enrichir le type",instruction:"Remplacez types/property.ts. Les équipements sont un tableau de chaînes ; floor? peut manquer, tandis que furnished=false est une valeur réelle.",action:"Remplacer entièrement",path:"types/property.ts",code:lessonTenPropertyTypeCode,expected:"Le type contient les champs de fiche sans donnée distante."},
{title:"Installer les quinze données enrichies",instruction:"Ne saisissez pas quinze descriptions. Remplacez entièrement data/properties.ts par ce catalogue fictif complet.",action:"Remplacer entièrement",path:"data/properties.ts",code:lessonTenPropertiesCode,expected:"Les quinze slugs restent uniques et chaque objet possède les informations de fiche.",visual:visual("10","enriched-data","Objet Property enrichi avec description équipements et disponibilité","Étape 3 — les nouveaux champs restent fictifs et locaux.",3)},
{title:"Centraliser recherche et navigation",instruction:"Créez lib/properties.ts avec le premier bloc, puis lib/property-navigation.ts avec le second. La navigation reconstruit uniquement les paramètres déjà validés.",action:"Créer",path:"lib/properties.ts",code:lessonTenPropertiesHelperCode,expected:"findPropertyBySlug retourne un logement ou undefined."},
{title:"Conserver l’URL de retour",instruction:"Créez ce fichier puis utilisez buildPropertyUrl depuis les cartes et buildResultsUrl dans la fiche.",action:"Créer",path:"lib/property-navigation.ts",code:lessonTenNavigationCode,expected:"Une fiche directe revient à /biens ; une fiche issue des résultats conserve les cinq paramètres.",visual:visual("10","return-context","Aller retour entre résultats filtrés et fiche avec la même query string","Étape 5 — le contexte validé voyage dans l’URL.",5)},
completeFile("lesson-10","components/PropertyFacts.tsx","Créer","Créez ce composant depuis le bloc entier. Il traduit chaque champ typé en information lisible sans recalculer le matching.","Surface, chambres, salle de bain, balcon, type, étage et statut meublé apparaissent."),
completeFile("lesson-10","components/PropertyDetail.tsx","Créer","Créez la fiche complète. Tous les imports, props, fallback d’image, équipements et messages de démonstration sont fournis.","Une fiche réutilisable affiche les données et le score existant."),
completeFile("lesson-10","components/PropertyCard.tsx","Remplacer entièrement","Remplacez la carte afin d’ajouter un lien Voir le logement séparé des futures actions interactives.","Chaque carte ouvre sa fiche et conserve son score."),
completeFile("lesson-10","app/biens/page.tsx","Remplacer entièrement","Remplacez la page de résultats : elle construit désormais detailHref avec l’URL validée au lieu de fabriquer le lien dans la carte.","Les quinze liens de fiche préservent filtres et tri."),
completeFile("lesson-10","app/biens/[slug]/page.tsx","Créer","Créez la route dynamique complète. Next.js 16 fournit params et searchParams sous forme de promesses : le code les attend avant toute lecture.","Un slug officiel affiche sa fiche, son score et ses métadonnées."),
completeFile("lesson-10","app/biens/[slug]/not-found.tsx","Créer","Créez la page dédiée aux slugs inconnus ; ne remplacez jamais notFound() par une fiche inventée.","/biens/inconnu affiche Logement introuvable et un retour vers /biens.")],checklist:["Les dix fichiers demandés sont fournis intégralement.","Quinze fiches sont accessibles.","Les champs avancés sont fictifs.","Le score réutilise calculateCompatibility.","Le retour conserve les paramètres.","Un slug inconnu appelle notFound().","Aucun lien n’englobe un futur bouton favori."],errors:[{problem:"La fiche est toujours introuvable",cause:"slug et donnée diffèrent.",correction:"Comparez params.slug et property.slug exactement."},{problem:"Le retour perd les filtres",cause:"Le lien utilise /biens en dur.",correction:"Utilisez l’URL reconstruite depuis les paramètres validés."}],exercise:["Ouvrez une fiche avec cinq paramètres.","Revenez et comparez l’URL caractère par caractère.","Testez /biens/slug-inconnu."],summary:["Créer une route dynamique.","Trouver un objet avec find.","Gérer notFound et les métadonnées.","Enrichir des données facultatives.","Préserver un contexte d’URL."]},
{id:webLessonCatalog[10].id,slug:"11",number:"11",title:webLessonCatalog[10].title,build:"Ajouter des favoris persistants uniquement dans le navigateur, sans compte ni serveur.",visibleResult:"Le cœur des cartes et fiches se synchronise avec /favoris et persiste après actualisation.",prerequisites:["La leçon 10 est validée.","Les fiches et leur navigation fonctionnent."],vocabulary:[{term:"Composant client",definition:"Composant utilisant les API du navigateur après hydratation."},{term:"use client",definition:"Directive placée en première ligne d’un composant client."},{term:"État React",definition:"Valeur dont le changement met l’interface à jour."},{term:"Contexte",definition:"Moyen de partager un état sans passer des props partout."},{term:"Provider",definition:"Composant qui fournit le contexte à ses descendants."},{term:"localStorage",definition:"Petit stockage persistant limité au navigateur actuel."},{term:"JSON",definition:"Format texte utilisé pour enregistrer le tableau de slugs."},{term:"Hydratation",definition:"Moment où React relie le HTML serveur au navigateur."}],steps:[
{title:"Comprendre les limites",instruction:"Aucun compte et aucune synchronisation : supprimer les données du navigateur efface les favoris. Seuls des slugs uniques sont stockés sous propertymatch:favorites:v1.",action:"Conserver",path:"Stockage local du navigateur",expected:"Vous savez expliquer pourquoi ce favori n’existe pas sur un autre appareil.",visual:visual("11","local-storage","Navigateur contenant une liste locale de slugs sans serveur","Étape 1 — aucune donnée ne quitte le navigateur.",1)},
{title:"Sécuriser lecture et écriture",instruction:"Créez lib/favorites.ts. Le code refuse JSON invalide, doublons et slugs inconnus, et tolère un stockage indisponible.",action:"Créer",path:"lib/favorites.ts",code:lessonElevenFavoritesCode,expected:"Seule une liste ordonnée de slugs officiels peut être enregistrée."},
completeFile("lesson-11","components/FavoritesProvider.tsx","Créer","La directive use client est nécessaire car le Provider s’abonne à un stockage du navigateur. useSyncExternalStore fournit un snapshot serveur vide : le premier HTML reste identique avant l’hydratation, puis tous les boutons reçoivent le même état.","Le Provider synchronise cartes, fiches et page favoris sans lire localStorage sur le serveur."),
completeFile("lesson-11","components/FavoriteButton.tsx","Créer","Le bouton lit le Provider. aria-pressed expose l’état vrai/faux aux technologies d’assistance ; preventDefault et stopPropagation empêchent le cœur d’activer le lien d’une carte.","Le libellé Ajouter ou Retirer et l’annonce visible suivent toujours l’état."),
completeFile("lesson-11","components/FavoritesGrid.tsx","Créer","Ce composant client filtre le catalogue avec les slugs validés et se met à jour immédiatement après une suppression.","La grille, le compteur et l’état vide utilisent le même store."),
completeFile("lesson-11","components/PropertyCard.tsx","Remplacer entièrement","Remplacez la carte du checkpoint 10. Le bouton cœur reste à côté du lien, jamais à l’intérieur.","Cliquer le cœur ne navigue pas vers la fiche."),
completeFile("lesson-11","components/PropertyDetail.tsx","Remplacer entièrement","Remplacez la fiche pour ajouter le même FavoriteButton près du résumé.","L’état du cœur est identique sur la carte et la fiche."),
completeFile("lesson-11","components/Header.tsx","Remplacer entièrement","Remplacez le header pour ajouter la destination Favoris dans les navigations desktop et mobile.","Favoris mène réellement vers /favoris et le menu reste accessible."),
completeFile("lesson-11","app/layout.tsx","Remplacer entièrement","localStorage n’existe pas pendant le rendu serveur. Le layout ne le lit pas : il transmet seulement la liste officielle des slugs au Provider client.","Toute l’application partage le Provider sans devenir entièrement cliente."),
completeFile("lesson-11","app/favoris/page.tsx","Créer","Créez la page serveur légère qui réutilise Header, FavoritesGrid et Footer.","/favoris affiche un total réel ou l’état vide."),
completeFile("lesson-11","app/biens/[slug]/page.tsx","Remplacer entièrement","Remplacez la route afin que origine=favoris produise un retour logique vers /favoris, après validation des paramètres.","Une fiche ouverte depuis les favoris revient aux favoris."),
completeFile("lesson-11","lib/property-navigation.ts","Remplacer entièrement","Remplacez le helper de navigation : l’origine favoris est reconnue sans modifier les paramètres de recherche existants.","Les deux contextes de retour sont déterministes."),
{title:"Tester la persistance",instruction:"Ajoutez depuis une carte, ouvrez /favoris, ouvrez la fiche, retirez, actualisez puis recommencez. Vérifiez aussi une valeur JSON invalide dans les outils du navigateur.",action:"Conserver",path:"http://localhost:3000/favoris",expected:"La liste reste cohérente et une donnée corrompue produit une liste vide, jamais une panne."}],checklist:["La clé exacte est propertymatch:favorites:v1.","Seuls les slugs uniques sont stockés.","Le SSR utilise un snapshot vide.","aria-pressed est présent.","Carte, fiche et page se synchronisent.","L’état vide est clair."],errors:[{problem:"Hydration mismatch",cause:"localStorage a été lu pendant le rendu serveur.",correction:"Lisez-le uniquement dans le store client après abonnement."},{problem:"Le cœur ouvre la fiche",cause:"L’événement remonte au lien.",correction:"Ne placez pas le bouton dans le lien et stoppez son événement."}],exercise:["Ajoutez deux favoris.","Actualisez /favoris.","Retirez-en un puis vérifiez la fiche correspondante."],summary:["Créer un composant client ciblé.","Normaliser du JSON local.","Partager l’état avec un Provider.","Éviter une divergence d’hydratation.","Construire un bouton accessible."]},
{id:webLessonCatalog[11].id,slug:"12",number:"12",title:webLessonCatalog[11].title,build:"Auditer l’application complète, exécuter les vérifications puis la publier directement avec la CLI Vercel.",visibleResult:"PropertyMatch est accessible sur une URL Vercel après des tests, un lint, un typecheck et un build réussis.",prerequisites:["Les onze leçons précédentes sont validées.","Accueil, résultats, fiches, 404 et favoris fonctionnent localement."],vocabulary:[{term:"Test",definition:"Vérification automatique d’un comportement attendu."},{term:"Lint",definition:"Analyse des problèmes de qualité du code."},{term:"Build",definition:"Préparation optimisée du site pour la production."},{term:"Déploiement",definition:"Mise en ligne d’une version construite."},{term:"CLI Vercel",definition:"Commande officielle qui publie le dossier courant."},{term:"Production",definition:"Version publique réellement consultable."}],steps:[
{title:"Faire la recette manuelle",instruction:"Testez au clavier accueil, recherche, tris, score, quinze fiches, slug inconnu et favoris. Contrôlez 390, 768, 1024 et 1440 px, les focus, alt, titres et absence de débordement.",action:"Conserver",path:"http://localhost:3000",expected:"Chaque parcours critique fonctionne sans souris.",visual:visual("12","quality-checklist","Checklist responsive accessibilité recherche fiches favoris et 404","Étape 1 — corrigez toute case rouge avant la publication.",1)},
{title:"Remplacer package.json",instruction:"Remplacez ce fichier complet. typecheck lance TypeScript sans produire de fichier ; lint analyse le projet ; test utilise le test runner léger intégré à Node.js ; build crée la version de production avec Webpack, mode stable qui évite les restrictions locales parfois rencontrées par Turbopack. Les versions restent celles installées à la leçon 2. Lancez npm install après ce remplacement seulement si package.json et node_modules ne sont plus synchronisés ; ne modifiez jamais package-lock.json à la main.",action:"Remplacer entièrement",path:"package.json",code:lessonTwelvePackageCode,expected:"npm run lint, npm test et npm run build existent réellement."},
completeFile("lesson-12","eslint.config.mjs","Remplacer entièrement","Conservez la configuration ESLint Next.js complète fournie.","npm run lint analyse TypeScript, React et les règles Next.js."),
...(["tests/data.test.mjs","tests/search.test.mjs","tests/matching.test.mjs","tests/property-details.test.mjs","tests/favorites.test.mjs","tests/accessibility.test.mjs"] as const).map((path)=>completeFile("lesson-12",path,"Créer","Créez ce test complet. Il utilise node:test et node:assert, déjà inclus dans Node.js : aucune grosse bibliothèque n’est ajoutée.","npm test exécute ce scénario avec les autres tests.")),
...(["app/layout.tsx","app/page.tsx","app/globals.css","components/Header.tsx","components/FavoriteButton.tsx","components/PropertyCard.tsx","components/PropertyDetail.tsx","app/biens/page.tsx","app/favoris/page.tsx"] as const).map((path)=>completeFile("lesson-12",path,"Remplacer entièrement","Appliquez la version finale complète d’accessibilité : lien d’évitement, focus visible, noms accessibles, retours d’état et styles responsive sont conservés ensemble.","Le checkpoint final respecte les contrôles manuels et automatiques.")),
{title:"Exécuter les contrôles",instruction:"Ouvrez Terminal > Nouveau terminal dans propertymatch. Lancez chaque commande séparément et ne continuez qu’avec un code de sortie réussi.",action:"Conserver",path:"Terminal VS Code dans propertymatch",commands:lessonTwelveCommands.slice(0,4),expected:"TypeScript, ESLint, tests et build réussissent.",visual:visual("12","terminal-success","Terminal affichant quatre contrôles PropertyMatch réussis","Étape 3 — un build réussi est la condition de publication.",3)},
{title:"Publier sans Git ni GitHub",instruction:"Lancez npx vercel. Si demandé, connectez-vous à Vercel dans le navigateur, confirmez le dossier courant et acceptez les réglages Next.js détectés. Pour la version finale publique, lancez ensuite npx vercel --prod. Ne saisissez aucun secret : PropertyMatch n’en utilise pas.",action:"Conserver",path:"Terminal VS Code dans propertymatch",commands:lessonTwelveCommands.slice(4),expected:"Vercel affiche une URL publique de production.",visual:visual("12","vercel-flow","Terminal vers authentification Vercel puis URL publique","Étape 4 — la CLI publie directement sans dépôt GitHub.",4)},
{title:"Vérifier la production",instruction:"Ouvrez l’URL Vercel dans une fenêtre privée. Rejouez recherche, fiche, retour, favori et 404 sur mobile. Les favoris de localhost ne sont pas transférés : ils appartiennent à chaque origine de navigateur.",action:"Ouvrir",path:"URL https://…vercel.app retournée par la CLI",expected:"La version publique correspond fonctionnellement au checkpoint final."}],checklist:["Les quatre largeurs sont contrôlées.","Le clavier et le focus fonctionnent.","TypeScript, lint, tests et build réussissent.","Aucun secret ni service distant n’est requis.","La CLI Vercel est utilisée sans GitHub.","La production est retestée."],errors:[{problem:"npx vercel n’est pas reconnu",cause:"La commande n’a pas téléchargé la CLI ou le réseau est indisponible.",correction:"Vérifiez Internet puis relancez npx vercel depuis le dossier contenant package.json."},{problem:"Le build échoue",cause:"Une erreur TypeScript ou un import subsiste.",correction:"Lisez la première erreur, corrigez son fichier, puis recommencez les quatre contrôles."}],exercise:["Ouvrez la production en navigation privée.","Effectuez une recherche avec trois critères.","Ajoutez un favori, actualisez et testez un slug inconnu."],summary:["Réaliser une recette accessible et responsive.","Exécuter typecheck, lint, tests et build.","Comprendre prévisualisation et production.","Publier avec la CLI Vercel sans Git.","Retester la version publique."]}
] satisfies readonly WebFoundationLesson[];
